<a href="https://colab.research.google.com/github/YashMishra17/Numpy-Tutorial/blob/main/NumPy_Tutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

**The** ***Basics***

In [ ]:
a = np.array([1,2,3]) # Intilizating Array 1D array
print(a)

[1 2 3]


In [ ]:
b = np.array([[0.9,0.8,0.7],[0.6,0.5,0.4]]) # Intilizating Array 2D array
print(b)

[[0.9 0.8 0.7]
 [0.6 0.5 0.4]]


In [ ]:
# How To Get The Dimensions Of Array Like 2D ana 3D
a.ndim


1

In [ ]:
b.ndim

2

In [ ]:
#Get Shape
a.shape

(3,)

In [ ]:
b.shape

(2, 3)

**How much memory our numpy array takes**

In [ ]:
# Get Size
a.itemsize

8

In [ ]:
b.itemsize

8

In [ ]:
# Get Total Size
a.size

3

In [ ]:
b.size

6

In [ ]:
a.size * a.itemsize
a.nbytes                    # Both Are Same

24

**Accessing/Changing specific elements, rows, columns, etc**

In [ ]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [ ]:
# Get a specific elements [r,c]
a[1,5]

np.int64(13)

In [ ]:
a[1,6]

np.int64(14)

In [ ]:
# Get a specific Rows
a[0,:]


array([1, 2, 3, 4, 5, 6, 7])

In [ ]:
a[1,:]

array([ 8,  9, 10, 11, 12, 13, 14])

In [ ]:
# Get a specific Coloumn
a[:,2]

array([ 3, 10])

In [ ]:
a[:,5]

array([ 6, 13])

In [ ]:
# Getting a little more fancy [startindex:endindex:stepindex]
a[0 ,1:6:2]

array([2, 4, 6])

In [ ]:
a[1:5:1,0]

array([8])

In [ ]:
a[0,1:-1:2]

array([2, 4, 6])

**Changing The Element Of arrays**

In [ ]:
a[1,5] = 20
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]


In [ ]:
a[1,4] = 21
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 21 20 14]]


In [ ]:
a[0,3]=14
print(a)

[[ 1  2  3 14  5  6  7]
 [ 8  9 10 11 21 20 14]]


In [ ]:
a[0,5]= 38
print(a)

[[ 1  2  3 14  5 38  7]
 [ 8  9 10 11 21 20 14]]


In [ ]:
a[:,2] = [1,2]
print(a)

[[ 1  2  1 14  5 38  7]
 [ 8  9  2 11 21 20 14]]


**Three Dimensional Array Example**

In [ ]:
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [ ]:
# Get a Specific Element (work outside in)
b[0,1,1]

np.int64(4)

In [ ]:
b[0,1,0]

np.int64(3)

In [ ]:
b[:,1,:]

array([[3, 4],
       [7, 8]])

In [ ]:
b[1,0,1]

np.int64(6)

In [ ]:
b[:,0,:]

array([[1, 2],
       [5, 6]])

In [ ]:
# Replace
b[:,1,:] = [[9,9],[8,8]]
print(b)

[[[1 2]
  [9 9]]

 [[5 6]
  [8 8]]]


In [ ]:
b[:,0,:] = [[6,6],[5,5]]
print(b)

[[[6 6]
  [9 9]]

 [[5 5]
  [8 8]]]


**Initializing Different Types Of Arrays**

In [ ]:
np.zeros(5)


array([0., 0., 0., 0., 0.])

In [ ]:
np.zeros([5,5])

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
np.zeros([2,3,3])

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [ ]:
np.zeros([2,3])

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
# All Ones Matrix
np.ones([1,2])

array([[1., 1.]])

In [ ]:
np.ones([1,2,2], dtype='int32')

array([[[1, 1],
        [1, 1]]], dtype=int32)

In [ ]:
# Any Other Number
#np.full(shape,value)
np.full([2,2], 55)

array([[55, 55],
       [55, 55]])

In [ ]:
# Any other number (full_like)
np.full_like(a,4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [ ]:
# Random Decimal Numbers0
np.random.rand(4,2,2)

array([[[0.16179347, 0.39004577],
        [0.06039485, 0.23448535]],

       [[0.12083189, 0.74504985],
        [0.71005642, 0.32866516]],

       [[0.57521631, 0.23043788],
        [0.77191477, 0.15697949]],

       [[0.91818244, 0.97663684],
        [0.01999842, 0.32883884]]])

In [ ]:
np.random.rand(3,3)

array([[0.193795  , 0.99171903, 0.34941213],
       [0.16577414, 0.7085741 , 0.31211083],
       [0.05355057, 0.68505836, 0.81342789]])

In [ ]:
# Random Integer Values
np.random.randint(7, size=(3,3))

array([[1, 6, 4],
       [0, 3, 0],
       [5, 5, 3]])

In [ ]:
np.random.randint(-4,8, size=(4,4))

array([[ 6,  5,  7,  5],
       [-2,  3,  2,  2],
       [ 3,  4,  5, -4],
       [ 4, -3,  6,  6]])

In [ ]:
# The Identity Matrix
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
# Repeating An Array
arr = np.array([1,2,3])
r1 = np.repeat(arr,3, axis=0)
print(r1)

[1 1 1 2 2 2 3 3 3]


In [ ]:
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3,axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [ ]:
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3,axis=1)
print(r1)

[[1 1 1 2 2 2 3 3 3]]


In [ ]:
# Question
output = np.ones((5,5,))
print(output)

z=np.zeros((3,3))
z[1,1] = 9
print(z)

output[1:-1,1:-1] = z
print(output)


[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


#### **Be Careful when copying array!!!**

In [ ]:
a = np.array([1,2,3])
b = a
b[0] = 100
print(a)                 # So it Give same output in print(a)  and print(b) so to get the proper Output We Have to use a Copy Function

[100   2   3]


In [ ]:
a = np.array([1,2,3])
b = a.copy()
b[0] = 100
print(a)

[1 2 3]


### **Mathematics**

In [ ]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [ ]:
a + 2

array([3, 4, 5, 6])

In [ ]:
a - 2

array([-1,  0,  1,  2])

In [ ]:
a * 2

array([2, 4, 6, 8])

In [ ]:
a / 2

array([0.5, 1. , 1.5, 2. ])

In [ ]:
b = np.array([1,0,1,0])
a + b

array([2, 2, 4, 4])

In [ ]:
a ** 2

array([ 1,  4,  9, 16])

In [ ]:
# Take The Sin
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [ ]:
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

###**Linear Algebra**

In [ ]:
# Mulitplication Of Matrix
a = np.ones((2,3))
print(a)

b = np.full((3,2), 5)
print(b)

np.matmul(a,b)


[[1. 1. 1.]
 [1. 1. 1.]]
[[5 5]
 [5 5]
 [5 5]]


array([[15., 15.],
       [15., 15.]])

In [ ]:
# Find The Determinant
c = np.identity(3)
np.linalg.det(c)

np.float64(1.0)

**Statistics**

In [ ]:
stats = np.array([[1,2,3],[4,5,6]])
print(stats)

[[1 2 3]
 [4 5 6]]


In [ ]:
np.min(stats)

np.int64(1)

In [ ]:
np.max(stats)

np.int64(6)

In [ ]:
np.min(stats, axis=0)

array([1, 2, 3])

In [ ]:
np.max(stats, axis=1)

array([3, 6])

In [ ]:
np.sum(stats)

np.int64(21)

**Reorganizing Arrays**

In [ ]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)

after=before.reshape([8,1])
print(after)

[[1 2 3 4]
 [5 6 7 8]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]


In [ ]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)

after=before.reshape([4,2])
print(after)

[[1 2 3 4]
 [5 6 7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [ ]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)

after=before.reshape([2,2,2])
print(after)

[[1 2 3 4]
 [5 6 7 8]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [ ]:
# Vertically Stacking Vectors
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2,v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [ ]:
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2,v2,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [5, 6, 7, 8],
       [5, 6, 7, 8]])

In [ ]:
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v1,v2,v2])

array([[1, 2, 3, 4],
       [1, 2, 3, 4],
       [5, 6, 7, 8],
       [5, 6, 7, 8]])

In [ ]:
# Horizontal Stack
h1 = np.ones((2,4))
h2 = np.zeros((2,2))

np.hstack((h1,h2))

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

**Miscellaneous**

In [ ]:
np.genfromtxt('Data.txt', delimiter=',')

array([[  1.,  13.,  21.,  11., 196.,  75.,   4.,   3.,  34.,   6.,   7.,
          8.,   0.,   1.,   2.,   3.,   4.,   5.],
       [  3.,  42.,  12.,  33., 766.,  75.,   4.,  55.,   6.,   4.,   3.,
          4.,   5.,   6.,   7.,   0.,  11.,  12.],
       [  1.,  22.,  33.,  11., 999.,  11.,   2.,   1.,  78.,   0.,   1.,
          2.,   9.,   8.,   7.,   1.,  76.,  88.]])

In [ ]:
filedata = np.genfromtxt('Data.txt', delimiter=',')
filedata.astype('int32')

array([[  1,  13,  21,  11, 196,  75,   4,   3,  34,   6,   7,   8,   0,
          1,   2,   3,   4,   5],
       [  3,  42,  12,  33, 766,  75,   4,  55,   6,   4,   3,   4,   5,
          6,   7,   0,  11,  12],
       [  1,  22,  33,  11, 999,  11,   2,   1,  78,   0,   1,   2,   9,
          8,   7,   1,  76,  88]], dtype=int32)

In [ ]:
filedata = np.genfromtxt('Data.txt', delimiter=',')
filedata.astype('int32')
#filedata = filedata.astype('int32')
print(filedata)

[[  1.  13.  21.  11. 196.  75.   4.   3.  34.   6.   7.   8.   0.   1.
    2.   3.   4.   5.]
 [  3.  42.  12.  33. 766.  75.   4.  55.   6.   4.   3.   4.   5.   6.
    7.   0.  11.  12.]
 [  1.  22.  33.  11. 999.  11.   2.   1.  78.   0.   1.   2.   9.   8.
    7.   1.  76.  88.]]


##### **Boolean Making and Advanced Indexing**

In [ ]:
filedata > 50

array([[False, False, False, False,  True,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])

In [ ]:
filedata[filedata > 50]

array([196.,  75., 766.,  75.,  55., 999.,  78.,  76.,  88.])

In [ ]:
## You Can index with a list in NumPy
a = np.array([1,2,3,4,5,6,7,8,9])
a[[1,2,8]]

array([2, 3, 9])

In [ ]:
np.any(filedata > 50, axis=0)

array([False, False, False, False,  True,  True, False,  True,  True,
       False, False, False, False, False, False, False,  True,  True])

In [ ]:
np.any(filedata > 50, axis=1)

array([ True,  True,  True])

In [ ]:
np.all(filedata > 50, axis=0)

array([False, False, False, False,  True, False, False, False, False,
       False, False, False, False, False, False, False, False, False])

In [ ]:
np.all(filedata > 50, axis=1)

array([False, False, False])

In [ ]:
((filedata > 50) & (filedata < 100))

array([[False, False, False, False, False,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])

In [ ]:
(~((filedata > 50) & (filedata < 100)))

array([[ True,  True,  True,  True,  True, False,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True, False,  True, False,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True, False,
         True,  True,  True,  True,  True,  True,  True, False, False]])